version: "2"

run:
  tests: true
  concurrency: 4

linters:
  enable:
    - govet            # Reports suspicious constructs and potential bugs.
    - gosec            # Detects common security issues in Go code.
    - unused           # Flags unused variables, constants, and functions.
    - funlen           # Enforces maximum function length for readability.
    - revive           # Style and best-practices linter (successor of golint).
    - goconst          # Finds repeated literals that should be constants.
    - depguard         # Restricts which packages can be imported where.
    - gocritic         # Opinionated checks for code style, bugs, performance.
    - ineffassign      # Detects useless assignments to existing variables.
    - gochecknoinits   # Forbids use of init() functions.
    - gochecknoglobals # Flags usage of global variables.
  default: none

  settings:
    funlen:
      lines: 80
      statements: 60

    revive:
      rules:
        - name: package-comments
          disabled: true

    goconst:
      min-len: 3
      min-occurrences: 3

    depguard:
      # Protect the domain layer from importing non-domain packages.
      rules:
        domain-strict:
          list-mode: strict
          files:
            - "src/application/domain/**"
            - "!src/application/domain/**_test.go"
          allow:
            - $gostd
            - capital-gains/src/application/domain

    gocritic:
      enabled-tags:
        - style
        - diagnostic
        - performance

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - funlen
          - gochecknoinits
          - gochecknoglobals
    generated: strict
    warn-unused: false

issues:
  uniq-by-line: false
  max-same-issues: 0
  max-issues-per-linter: 0

output:
  formats:
    text:
      path: stdout
      colors: true
      print-linter-name: true
      print-issued-lines: true
